/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   init.js                                            :+:    :+:            */
/*                                                     +:+                    */
/*   By: fbes <fbes@student.codam.nl>                 +#+                     */
/*                                                   +#+                      */
/*   Created: 2022/03/27 03:00:23 by fbes          #+#    #+#                 */
/*   Updated: 2022/03/27 03:00:23 by fbes          ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

// this script initializes all global functions and variables for use elsewhere
// in this extension's content scripts

// inject script to apply framework functions to elements generated by Improved Intra
// only inject it on the subdomains of *.intra.42.fr
if (window.location.origin.indexOf(".intra.42.fr") > -1) {
	const s = document.createElement('script');
	s.src = chrome.runtime.getURL('generic/inject.js');
	(document.head || document.documentElement).appendChild(s);
}

// global variables
const improvedStorage = getSessionStorage();
const portName = (chrome.extension.inIncognitoContext ? "incog_comm" : "normal_comm");
